#ifndef __GYRO_ERROR_H
#define __GYRO_ERROR_H

typedef enum {
	NO_ERROR = 0,
	ERROR_NULL_POINTER,
	ERROR_VALUE_NOT_IN_RANGE,
	ERROR_DEVICE_NOT_INITIALIZED,
	ERROR_DEVICE_ID_NOT_VALID,
	ERROR_NO_DATA_RECEIVED,

	EROR_LAST_ERROR
} gyro_error;

#endif
